export type ChangelogTag = "design" | "content" | "engineering" | "fix";

export interface ChangelogEntry {
  date: string; // ISO, used for sorting and display
  title: string;
  tags: ChangelogTag[];
  what: string;
  why: string;
}

// Newest first. One entry per meaningful push (or tight cluster of pushes),
// written like release notes: what shipped, and the reasoning behind it.
// When you ship a change to this site, add an entry here in the same voice.
export const changelog: ChangelogEntry[] = [
  {
    date: "2026-08-31",
    title: "The last two experiment covers go live too",
    tags: ["design", "content"],
    what: "Schematic's card now shows its actual site: the wine-dark hero with the wireframe form. Personal Color Analysis shows its landing (Find your perfect color season) and finally carries its live link, so all six experiments now open to the real thing. Every card on the experiments shelf is a screenshot of running software.",
    why: "The shelf's whole argument is 'these exist.' The last two illustrations were the only cards still saying 'trust me' instead of 'look.'",
  },
  {
    date: "2026-08-31",
    title: "The experiments move up a shelf",
    tags: ["design"],
    what: "On Work and on the home page, the Experiments section now sits directly under Professional Work, with the archive closing the page instead of splitting the middle. ARND, live and current, is the second thing you meet; the oldest material is the last. The filter pills follow the same order.",
    why: "Reading order is an argument. The professional work makes the case, the live experiments show the range, and the archive is the epilogue, not the second chapter.",
  },
  {
    date: "2026-08-31",
    title: "The ARND story goes end to end",
    tags: ["content"],
    what: "The ARND case study now shows the whole arc, not just the app. Three more screens cover the loop (the show page, proof-by-check-in, the performer's side), the arnd.app front door and per-event cover art show the brand carrying through, and a new Run in the open section shows the public changelog (a hundred-plus updates, each with its why) and the governed design system page. Screens sit in a compact row now instead of stacking full-width.",
    why: "Designing an app is the visible half. Running one, with a brand, a changelog culture, and rules that outlive the author, is the half a portfolio rarely gets to show.",
  },
  {
    date: "2026-08-31",
    title: "Phone screens stopped hogging the page",
    tags: ["design", "fix"],
    what: "Portrait app screenshots in case studies used to stretch to the full reading column, which made a single phone screen taller than the whole viewport, two and a half screens of scrolling for one image. Tall captures now render at phone size: centered, rounded like a device, with a soft shadow and a centered caption. Applied to ARND's three screens and the tall captures on the automation and Orchid studies.",
    why: "A phone screen shown at phone size reads as a product. The same screen blown up to fill the column reads as an obstacle.",
  },
  {
    date: "2026-08-31",
    title: "The experiments shelf shows the real things",
    tags: ["design", "content"],
    what: "The Experiments section on Work is a denser three-up shelf now: cover, category, and the app's name, nothing else. And the covers stopped being abstract stand-ins. ARND's card is two real screens from the app (the feed and the live Toronto map) on its own bellflower blue; Mooze, Vesta Press, and Toronto Yuwol show their actual landing pages, captured from the live deployments. Schematic keeps its schema-tile grid and Color Analysis its four-season palette, since those are the product.",
    why: "Four of these six are live software. A shelf of real screenshots says 'these exist and you can open them' in a way no illustration can. It also fixed a quiet embarrassment: ARND's old cover was orange, and ARND has never been orange.",
  },
  {
    date: "2026-08-31",
    title: "Quieter everywhere: the minimal pass",
    tags: ["design"],
    what: "Three subtractions. The dual clock (Toronto and Seoul) left the header, where it was decoration on every page, and moved to About, where it's biography. The guide now lives on the home page only: a smaller, calmer card with a plain link instead of a button, and if you close it, it stays closed for the rest of your visit. And the site's small uppercase labels, which had drifted into nineteen slightly different sizes and letterspacings, now share one spec.",
    why: "Minimal isn't a look, it's a discipline: every element either earns its place on every page it appears on, or it moves to the one page where it means something.",
  },
  {
    date: "2026-08-31",
    title: "ARND joins the front door, as itself",
    tags: ["content"],
    what: "ARND's case study stopped calling it a thought experiment, because it stopped being one. The rewrite tells the current story: a working app running on live curated Toronto listings, in beta at arnd.app, with real screens from the app itself (the map on live data, the feed, a hosted listening night). It now leads a self-built Experiments section on the home page, under the professional flagships, and its live link points at the real domain.",
    why: "The judges who shaped the flagship shelf read the old write-up and fairly called it a concept piece. It isn't one anymore, and the portfolio should say what's true now.",
  },
  {
    date: "2026-08-17",
    title: "The home page stopped shipping the animation engine",
    tags: ["engineering"],
    what: "The motion library was loading on every page, roughly 128KB of JavaScript, even though the home page used it only for a hover lift and an icon swap. Those are plain CSS now, the magnetic card effect is a few lines of hand-rolled motion, and the floating guide loads lazily after the page is interactive. The home page no longer downloads the animation engine at all; it now loads only where it earns its place, on the Work grid and the gateway. The animations look the same.",
    why: "The fastest code is the code you don't send. A portfolio should open instantly, especially for someone skimming on a phone between meetings.",
  },
  {
    date: "2026-08-17",
    title: "The work has flagships again",
    tags: ["content"],
    what: "The home page used to feature nearly every project, which meant it featured nothing. It now leads with four: the transaction-workflow redesign, the Orchid design system, the Aplos and Keela integration, and the fee opt-in experiment, the pieces that best show senior product work. Two more sit behind them for range. Every other case study is still here, one click away under Work; they just no longer crowd the front door.",
    why: "A portfolio that features everything is a list, not a point of view. Choosing what leads is one of the more honest things the home page can do.",
  },
  {
    date: "2026-08-17",
    title: "Tightened the layout and framed the work",
    tags: ["design"],
    what: "The Work and Writing pages got an editorial masthead: the title on the left, the one-line description on the right, so the header fills the width instead of hugging one corner. Every project cover now carries a consistent hairline frame, so a bright product screenshot, a color field, and the blurred confidential card all read as the same kind of object. The guide card is fully opaque now, so a decorative sticker can no longer show through it on the About page. And the Résumé page finally spells its own name with the accents the nav already used.",
    why: "These were small distances between things that were supposed to match. A portfolio that pays attention to its own edges is most of the argument.",
  },
  {
    date: "2026-08-17",
    title: "Quieter foundations: recovery screens, lighter images, first tests",
    tags: ["engineering"],
    what: "Three things under the hood. If a page ever throws, you now land on a branded recovery screen instead of a raw error, on any route, and even if the whole layout fails. The three heaviest case-study images were re-encoded from PNG to JPEG, cutting about 2.8MB off those pages with no visible change. And the content pipeline, the rate limiter, and the two write endpoints now have a test suite, so the parts that quietly matter can't break unnoticed.",
    why: "None of this shows on a good day. It is what keeps a bad day from turning into a broken one.",
  },
  {
    date: "2026-07-03",
    title: "Added Schematic, retired Wayfind, linked ARND live",
    tags: ["content"],
    what: "New case study: Schematic, a 2016 design-research project on the 18 maladaptive schemas from schema therapy, rebuilt in 2026 as a navigable archive with a private browser-only self-check. ARND now links to its live alpha, and Wayfind came off the shelf. Mooze, Vesta Press, and Toronto Yuwol keep their live links.",
    why: "Schematic is real design research, not a weekend build, so it earns a place. And the work should show what's live and current, not what's stale.",
  },
  {
    date: "2026-07-03",
    title: "An accessibility and legibility pass",
    tags: ["design", "engineering"],
    what: "Audited contrast, motion, and reading comfort. The paper grain moved behind all content so it textures the page without ever sitting on top of the words. Reduced motion is now honored everywhere: framer-motion animations disable for anyone who asks (one setting at the root), plus a CSS reset for transitions and smooth scroll. The ambient dual-clock in the header is hidden from screen readers, since it is decoration, not information.",
    why: "The audit found the fundamentals already sound (every text color passes AA, the reading measure is a comfortable 68 characters), so this was about the edges: texture that respects the text, and motion that respects the person.",
  },
  {
    date: "2026-07-03",
    title: "Varied the closing line on three case studies",
    tags: ["content"],
    what: "Orchid, Aplos x Keela, and Forkable all ended on the same construction: 'the thing I'm proudest of isn't X, it's Y.' Once a reader notices a template, it stops reading as reflection. Rewrote each closer to land the same real point in its own words.",
    why: "Repetition across strong case studies reads as formula, and it undercuts writing that's otherwise specific and earned.",
  },
  {
    date: "2026-07-03",
    title: "Rewrote the experiments as design stories",
    tags: ["content"],
    what: "Mooze, Vesta Press, Wayfind, and Color Analysis read like feature lists with a tech stack attached, which for a design portfolio quietly says 'I prompted an AI to build this.' Rewrote each to lead with one real decision: Mooze designs for the return not the save, Vesta refuses to summarize, Wayfind is built for one hand on one trip, Color Analysis is tactile instead of a verdict. Cut the feature bullets and the stack sections; the tools already sit in each case study's meta.",
    why: "A side project should still show taste and judgment. The point of these was never the stack, it was the call I made and why.",
  },
  {
    date: "2026-07-03",
    title: "The side projects go live, for real",
    tags: ["content", "engineering"],
    what: "The Claude-built experiments that are actually deployed now carry a 'Visit the live app' link on their case study, so you can open the real thing instead of only reading about it: Mooze, Vesta Press, Toronto Yuwol, and Wayfind. Only verified-and-public deployments got linked.",
    why: "A case study says I built it; a live link lets you use it. For self-shipped software, the proof is that it runs.",
  },
  {
    date: "2026-07-03",
    title: "The vault steps out of the nav",
    tags: ["design"],
    what: "Same-day edit: Vault left the header nav and now lives in the home page's right rail, under Now, where the wandering begins anyway. Also cut the repetition that had crept in: the vault feed no longer mirrors now-snapshots, and the hero links dropped About and Resume, which the fixed header already offers a glance away.",
    why: "The header is for the hiring path; the vault is for wanderers. And saying something twice on one screen is not emphasis, it is noise.",
  },
  {
    date: "2026-07-03",
    title: "The vault opens",
    tags: ["design", "content", "engineering"],
    what: "New direction made structural: /vault is a living record that weaves notes, moments, frames, and artifacts with the essays and now-snapshots the site already had. /now keeps every dated snapshot instead of overwriting, so it shows the path, not just the position. An importer stands ready to bring curated posts over from a decade of Instagram, original dates intact. Vault joins the nav.",
    why: "A portfolio shows what Allen made; the vault records who he was while making it. Provenance over polish: timestamps, reversals, and things in progress are the point, not a liability.",
  },
  {
    date: "2026-07-03",
    title: "Paper grain, and a warm dark canvas to match",
    tags: ["design"],
    what: "Added a faint paper grain: fine grayscale noise, overlay-blended so it adds tooth without dulling the page, tuned to a whisper. One texture covers both themes. Warmed the dark background from a cool near-black to a warm ink so both modes feel like the same paper.",
    why: "Organic grain reads as material, not the geometric pattern that made the dot grid feel like a glitch. This is the tactile half of paper; the ivory tint was the color half.",
  },
  {
    date: "2026-07-03",
    title: "Warmed the canvas to paper ivory",
    tags: ["design"],
    what: "Shifted the light background from a cool near-white to a warm ivory. Pure color, no pattern, so it reads as paper stock instead of a screen. A nice side effect: the stickers' white die-cut borders pop a little more against it.",
    why: "The honest way to add paper warmth is the material itself, not a texture laid on top. This is what the dot grid was reaching for and failing to be.",
  },
  {
    date: "2026-07-03",
    title: "Cleaned the canvas: no cursor, no grid",
    tags: ["design"],
    what: "Removed two decorations in one pass: the trailing ring-and-dot cursor and the background dot grid. The grid got three tries (too faint, then distracting, then crisp but still competing), and the cursor's ring read as a glitch over it. Native pointer, bare cream canvas.",
    why: "When a decoration keeps fighting you, it isn't earning its place. The work, the writing, and the stickers carry the personality; the background should recede so they can breathe.",
  },
  {
    date: "2026-07-03",
    title: "Redrew the stickers that didn't read",
    tags: ["design"],
    what: "Audited the About stickers at their real size. The paintbrush read as a lipstick, the clarinet as a chess pawn, and the guitar as a gourd. Swapped the brush for a paint palette with color dabs, angled the clarinet so the keys and mouthpiece show, gave the guitar a proper figure-eight waist and round sound hole, and tightened the trumpet bell and capybara.",
    why: "A sticker that needs a caption has failed. If it can't be read in a glance at margin size, it is noise, not personality.",
  },
  {
    date: "2026-07-02",
    title: "One accent color, and a lighter codebase",
    tags: ["design", "engineering"],
    what: "Gave the site a single signature color, drawn from the 묵 seal: highlight any text and it glows seal red, and focus rings switched from a generic blue to the same. Stickers now peel up on hover so they read as grabbable. Under the hood, deleted an entire orphaned layout-switching system (six components) that nothing rendered anymore.",
    why: "The palette had one off-brand color left, the blue focus ring, in an otherwise ink-and-cream site. One accent used sparingly is identity; used everywhere it is wallpaper. And dead code is a tax every future change pays.",
  },
  {
    date: "2026-07-02",
    title: "Sticker round two: the ones with stories",
    tags: ["design"],
    what: "Four more for the About scrapbook: a film camera, a loaded paintbrush, a red seal carved with 묵, and a capybara with an orange on its head. Each is placed beside the paragraph that explains it; the seal sits next to On the name, since Mook is a homophone for ink.",
    why: "The best sticker is one that makes you ask why it is there, and the page answers. The capybara is the retired site mascot, enjoying its afterlife where it can no longer interrupt anyone.",
  },
  {
    date: "2026-07-02",
    title: "Pixel stickers land on the About page",
    tags: ["design"],
    what: "Nine hand-pixeled, die-cut stickers scattered scrapbook-style down the About margins: a running shoe, the Korean and Canadian flags, Jacob Collier, Hiromi, and a clarinet, trumpet, guitar, and piano. They drag, and your arrangement is saved locally. Drawn pixel by pixel with a render-and-review loop; the runner figure took three attempts and lost to the shoe.",
    why: "The About page told the story in words only. Stickers are the margin-doodle layer: the things I love, drawn the way I loved drawing as a kid.",
  },
  {
    date: "2026-07-02",
    title: "A second audit, and the work grid gets its proof back",
    tags: ["fix", "engineering"],
    what: "Re-audited the whole site from recruiter, designer, and engineer seats. The flagship card on the work grid now leads with its 75% to 92% result instead of an unlabeled blur, the guide stays closed on browsing pages, ESLint went from seven problems to zero, and dependencies got patched.",
    why: "An audit only counts if you run it again after the fixes. The second pass caught a label that had been invisible all along: white text on a cream blur.",
  },
  {
    date: "2026-07-01",
    title: "Instant first paint, visible results, honest thumbnails",
    tags: ["design", "engineering"],
    what: "Replaced hydration-gated reveal animations with pure CSS so pages paint immediately. Un-blurred the Fee Opt-In results infographic, drew five cover marks to replace near-black screenshot thumbnails, and gave the wide-screen home a small Now rail.",
    why: "First visits started with two seconds of blank screen, and the best case study was hiding its own outcome. Aggregate results are not confidential; product screens are. The blur now knows the difference.",
  },
  {
    date: "2026-06-30",
    title: "The availability pill comes off",
    tags: ["content"],
    what: "Removed the green Open to roles indicator from the home hero.",
    why: "The work should make the case before the status does. The About page still says it in full sentences.",
  },
  {
    date: "2026-06-29",
    title: "Sharing layer: sitemap, robots, one clean share card",
    tags: ["engineering", "fix"],
    what: "Added a sitemap and robots file, then caught my own duplicate: a second generated share image was fighting the hand-made one, so the generators went and the branded card stayed.",
    why: "Links to this site get pasted into Slack and LinkedIn by people deciding whether to talk to me. The preview is the first impression before the first impression.",
  },
  {
    date: "2026-06-29",
    title: "Earned Black, and every em-dash leaves the site",
    tags: ["content"],
    what: "Published Earned Black, an essay on rank, ink, and what depth you cannot shortcut. Retitled two essays and two case studies away from formula. Removed all eighty em-dashes from the site, each replaced by the punctuation the sentence actually wanted.",
    why: "Titles that read like content marketing undercut writing that is personal. And the dashes were a tell: machine cadence in what should be a human voice.",
  },
  {
    date: "2026-06-27",
    title: "The guide wins; the chatbot goes",
    tags: ["design"],
    what: "Shipped a streaming AI chat grounded on the portfolio, lived with it for an evening, and removed it the same day. The curated guide took its place and became a real navigator: per-page notes, next-step links, quick nav.",
    why: "The chat felt off. An open prompt invites anyone to test the edges; a curated voice says exactly what I want said. Killing your own feature quickly is a feature.",
  },
  {
    date: "2026-06-27",
    title: "The flagship becomes a feature card",
    tags: ["design", "content"],
    what: "The home page now leads with the Fee Opt-In study as a feature card: the 75% to 92% result over the redacted cover, with a confidential chip. Contact moved to allen@mooque.xyz, and the gateway forms got rate limiting, honest error states, and proper tap targets.",
    why: "The strongest evidence was buried in a list. If the work is confidential, lead with the outcome and say why the pixels are blurred.",
  },
  {
    date: "2026-06-24",
    title: "From capybara to quiet",
    tags: ["design"],
    what: "Retired the animated mascot era: a pixel avatar, Clippy, the Windows XP dog, and a custom capybara all had their day. What remains is a small text guide that knows which page you are on.",
    why: "Four mascots taught me the personality belongs in the words, not the sprite. Charm that interrupts reading is not charm.",
  },
  {
    date: "2026-06-24",
    title: "Images: 198 MB to 33 MB",
    tags: ["engineering"],
    what: "Resized and re-encoded every case-study image, fixed uppercase filenames that broke on case-sensitive servers, and pruned dead mascot code and assets.",
    why: "Case studies were shipping raw design-file exports. And macOS forgives filename casing; Linux does not.",
  },
  {
    date: "2026-06-24",
    title: "Experiments join the portfolio",
    tags: ["content"],
    what: "Added the Experiments section: Wayfind, ARND, Vesta Press, Mooze, Toronto Yuwol, and Personal Color Analysis, alongside the full personal-project arc from illustration to design systems.",
    why: "The range is the point. Side projects show judgment with no one else in the room.",
  },
  {
    date: "2026-06-23",
    title: "First branding pass: favicon, share card, adaptive theme",
    tags: ["design"],
    what: "Hand-set the ak favicon and share card in the wordmark style, added a theme color that follows light and dark mode, and gave the 404 page the site's typography.",
    why: "The details nobody asks for are the ones designers check first.",
  },
];
